- name: Setup Python and Virtualenv
  hosts: terraform-ansible
  become: yes
  tasks:
    - name: Update apt cache and install python3, virtualenv
      apt:
        pkg:
          - python3
          - python3-pip
          - virtualenv
        update_cache: yes

    - name: Create a virtual environment
      command: virtualenv /home/ubuntu/lab/venv

    - name: Install Django and Django Rest Framework in virtualenv
      pip:
        virtualenv: /home/ubuntu/lab/venv
        name: 
          - django
          - djangorestframework

    - name: Start Django project
      shell: |
        . /home/ubuntu/lab/venv/bin/activate
        django-admin startproject setup /home/ubuntu/lab

    - name: Changing the ALLOWED_HOSTS in the settings file
      lineinfile:
        path: /home/ubuntu/lab/setup/settings.py
        regexp: '^ALLOWED_HOSTS = .*'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
