- hosts: terraform-ansible
  tasks:
   - name: Create the index.html file
     copy: 
       dest: /home/ubuntu/index.html
       content: "<h1>Created with Terraform and Ansible</h1>"
   - name: Start HTTP server
     shell: "nohup busybox httpd -f -p 8080 &"    